# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:jLRsYsfcNIcNbd1bZ/2RSUgKvJXGj6PSrJ/ggUhRdi5b9SMRxMD5jm+BNnKCo+uAjpXK9v/EDRqxf3A7qkQK751rHoJ+8Gh2GpazgmT2eBdu5ovYCQSn1/jk+yHZ8meu+Dp6EhuQh+DQPjuW3SpXl/9AfdFMD6Rr/9VV11VEaVOK9WGGCTewRqGYAeKb5tiIDXn47N70US78YhFbjCg7Pa0FReqyzkb+W0fKO7+7hg==,iv:AGugYT7LNC+9fICyMDaBPp8uicANYi8LIqyL9/ChSUM=,tag:2b0/HGTPlktbFobnRjkytQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0REtUZGZGOVZvQlR3UlNJ
        UEw5djFMOUpHc21NTUpRK3RoODJ5cUVTeWt3ClRxalhrQWJFL3VoU3c0Z0EvdC93
        VE5zZGQ1Ri82MzZOUm5UNzhEV2Fsdm8KLS0tIFZVZ1BZQ1hGaE1SaWFuTGFOWUJE
        SU1KbkJhM29QMnhROEF6bXhGaHd4UjAKhBLrK/c2ea3MZQWyNo3J3BWIY1BGStuz
        3eJDtJLITNhMZ/rC5E1Kr3WXp6i761q/OgB1Fm/6t3oRAbz3gjSdtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T12:36:56Z"
  mac: ENC[AES256_GCM,data:LttV6Bvnlqqu246+eK7ZHbhq1ZJiQuRwu8yFmJ0vtGfLPQ9aOFxti/dXfk8/4woNxF4ABLg582rMj0KATFmuFZsYD1OjIOkIA9z55YbwCVzDkmrUrFnEsIOu6QoTOP3VJBD8Vs+WVSAVWh8xVcHY9CwLU4bgg13uAQkW0rMeS2I=,iv:MBM5a6wn3uRtzFO6AvvsYe3e0CmMSKrozPN9kHgtIbY=,tag:1lBtVlAUjW/OEPz07Jowmg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
