# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:NJ1Giz/JBs2lf5olNR7I1JisFOo3mDL2UbrbM+eDTaL6uVWhVogOxg8hBeDI9dTjs5igox+vqkMsg04FhuxHYXQWVRajy0RtkTJtn78CSy1cRqtCbCzsb2CdMrVnCZBn+tSkGaXGsayvJWEM5jwB2/6XJXs1x6TNEQXah289RBSO3RLogK3rCG0YLkn2mncdxsSTerSXlcTS6xmpAWBnWsY6fLBCYZn0M8gnDg/OPA==,iv:JvmZIEoY722DfgFmsV3Sp4LCdPAGnd5s6rh0UPmUg2E=,tag:j3s/zIEV/fS7w0xSMFA9wQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dktCbUlhcnJsZ2FSMjBK
        L2lmaVFobWp3dzRvSmJEa1FsV1ZDOXZHVEZzCnowaXJIV0hWM3B5ZkNVWmlGTE5s
        YW5wVFBiU1h3eStOSXBtL09ULzhqR1UKLS0tIGVLY0NzQncvT0cwK21DS3owNldy
        bm9wTXloOWNFRGZNVlJqc3ZkbmZKa2sKga37MyLb0mZfPAdqyFT/aaLPPTc4/4+f
        CNpIGf8JtijzrdHXmfFmNJ8fHwxkRh66BWNVK15c6/ABGN1y/gULnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T11:51:22Z"
  mac: ENC[AES256_GCM,data:R7/ky30fIvcxFWitAsSJKT+gMHVylsTtdfVxPIaMl10KVU5QKC3EKxzbdgHxxJMtcUid7YOVYwCApduQCFu6s4HoYkSMv0dEyKwQ0je0f4URMhK746I33shmEiBo62EdG5UOSxu0EdO3mUGJXepGMv/Ukcs6PfsZ1HNi98eoYuY=,iv:titdQqnx9Qs+5SV1aYTlcEEb5NzK2h8Li38ThKXze/I=,tag:EE7qUZxkoN+8ECmWtYZaig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
