# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:rlGW2DdNlb/SEEB60Jv5lT1Rs8zwWJBdXNOV48zEl2pz1pNnJYvQ2TrJHIcHJAfliIbgaYcK6rL0kx9iKL5IBfLT3w/RmmvkObbyU4VbrfnyJcxSNrkfLboEjPaei9kuZUJMD3Jv6U8CgkFvmrgwan6Ag7SZ4Nnuo/i/F3sfPeAxAgcgj0X3pNY3IfAqxks+BodAgq4I4aC4mJg4k7o/4OVRUT0wpao2cTLqe4BIng==,iv:QdVpJfkUx8ck8cI3Y7V2ZEiXZamHO2LntqiDhmzR3ZQ=,tag:B+AJdfgU4oIGvCDlB8pqLw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdzU4SHVJcWV5Qnc5cjVR
        QnJLQXhybWtSbFFHNlhMbXUzeDE5U2crc0RNCkFkRFVkNUtWZ3dEdXJzeFh2Y1lN
        ZjVOZHc3dUQwU1JYODU3bHFiNFkrbW8KLS0tIFpOTHJQdS9SMDhnSW1tNWtkZDU3
        MytWME50cDFRVU40TEllZndjazlTeDgKVpJ9QWqpDjVsptSV99Ds3MmGF8T46zZR
        ji/D2gUnPO1rQGiR+KNbO2Q9Epzl4gi+cl3ORqWjx7j5L6kTDAOUiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T15:24:57Z"
  mac: ENC[AES256_GCM,data:z0PvrrSJyqDwZXFfZ7j+GTMySdw8AeZEqcuOcLRml77pkN0KLBgTJBbBK1XeZT5bEbG4zUsi/jKvbbA0i5ALDOUUpi43ndyicZ7e5uF6EW384TGDbaweGy0k/EEc8ZQEMG2hT5bwruF7wS1i9RE7NYdbHHKQoHcFRb2dHblWYHI=,iv:btR60hRnazM4x9QYZmTT+FZnG0DxrSrTQr3FzegycOo=,tag:IQOJ3YOdwBZhixMD3QMFtA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
