# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:R8S+n+tr9Oj/T8JmlG+EHwLHYmvCXQlF5XfG9LITIDU0isTMnw7PEw==,iv:XHdLM4QQ9qwDwx9Ev/IA+D/3hiTW2JJ6WQslXHKaQkk=,tag:L8i9js2BcBBlRyUg1X9GiQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV0NNMGV3Q0U4OW1vc1d2
        YmZmYTVRK2VwUVFjdUE2SnljSC9Kb1FUaTNVCnJBa2VlWGsvbnZXWmtTOEVqdFds
        V1p0NFdLNkNJUTNpenByenVvWFJuaUkKLS0tIHhibGpiN0NWeFlBRlVMQzdBYVhO
        KzNIVkxkdDh3MkJDOG1zdmdTUkl3elkKcbuJDFKb0k8ajEQ5tVntHfu51ZRkXgmL
        g9Im9SaqpQ4iadb8MYM7dpCju9yogKz0TgtjfLeFKnE8L6mIoqqanQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T09:46:51Z"
  mac: ENC[AES256_GCM,data:oNgXSgz8TFTilvpYlFoRGpUMIZpNwT5kZzsjZPiq6ZhEXbYJMun0s+0iSjVz0jhF6IKlya1uMQ6MfMOkTrQCE9rH5Ruv/o27ImZS6mHS/3lx5qWHc+lAzpTok08hw4JkgQfneCdR6+U5MZd8OAWhV/EkHnpT+Crwtb1zk5gbYUY=,iv:HhuK4Lh/jl3r+AC36GoxfHOl7fHkoTj/qKHNyr0jY4U=,tag:xkidxvkh5x9KaSMTYpnJWA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
