# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:v20/3wkOBaHe5rfS3Y2udc6cC5MUJvfax2E0SQve+Pf4tKmD6Y8VnQ==,iv:Gxdwc2hHJIsuu4OQcAJyDXhTT6fyjgkHuCex1oH1OLI=,tag:iq3rzb5dmOl+sGvrquK/HQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcVZZYXVweXlKK1BHN2V2
        SVBTWUQ1NTRGQzNOWXNOZVJkMmlRRHNjT2hRCk0zRXpEYkdaSUtUTTN0cW5XZ1Bx
        RFlQQkFYTzB2aXluT050NlE2TS9SUHcKLS0tIHpXd2pLNnJKV2pDczczVTZUMjQ4
        MFMvUWUzeHpUNzA5VlQwRmNFL3djdEUK3SnbDPPsRDjUzRMWMzkUEFPRPFwmq53d
        0FJf+lCW6N9fVpM3t5CeEPPk74UV9MJ5CcSGce276F+2LmPQ6ksCWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T11:32:39Z"
  mac: ENC[AES256_GCM,data:tDSq5pwDbn4iEFpoGFw896GYKsH2ZMmru8Sz2wg9/Olds8hzv4hg+BfVDRaaDr1lIOv1m+/6o4zR6Ykk8aCVay3UCVU0p6yB/y7k+E9/gdZQuB4g4bzUUQDaj+QS+j7vpzaRCAP5HL4LdfPpv7NsEHIyfRUmI3uYBYXdp3LPHWg=,iv:BN9JK/8X3ZacYwfKru3Q1B97/eSiPOdodeVBH/0RdAs=,tag:UI9s9S+WnpR5Sx8H1VIDfQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
