# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+OjKjZobgqI2rVMn+31FSjlECU646xdmwJ5uE16oWuU=,iv:xC7a5ELo4lY80S3yXvCZXBzTqQ2GqFxxw3r3eI5xd74=,tag:pZ1A0r3oRQnngZW/CO4d1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUUZOYkhtbSsrVFRYZm9k
        NVJBcFpKb214MzJ1SXRtS01TNG54NXhHazFNCk5EdElpREQxU0Vpa3ZIZDQxenZm
        blZzanRBNHZBeDhPTXI3bmp4WExXcXMKLS0tIFljZnUvK3VYNWhCVDhGcTBzbWda
        bXV0TzRxOHMwTE5lc1dWOS9HS3hzUVkKntanrfQhQaNvQxVQWULNaZcMkOahEDNY
        EqBzziZy/SwMisn15mFKIsehflUGXbyYE3YzlBhauXf6AoO/14E4Zw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T15:24:57Z"
  mac: ENC[AES256_GCM,data:KV2tBT7btzfjVlY2u04X4LQIpbqtnTm7atL3tCe5A0TxLpXcqY37GA9GS2wJUMAdMvrVsVmVHiccJTQ9qfpogzZCZfrTHHY6UEzW5lWLzp1Hy4uhivHxHHRP5LlGb0dmhMxuiX3BnbcChaDGyFGj1/Y+pUzFi0yqfwTK8UmyuvA=,iv:TkBDBP0QR+vHQx1b0razkIMqff9yFGK7P/Lz9d7LDDc=,tag:7ogzxNBPWfRTdBabr7485g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
