# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:0BcdexWA70oFLcRsq244Q9BGyEiGdsrJxAeX45Byw5E=,iv:t9lz0GmUEHOWI58VfQWtj9kU0F2+ZCKK8jDk6+imzw8=,tag:mcKxw12fiWinOAmMwTnvVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSnRtRWkxYVErMmZVQ3h5
        S0JFVGt0WGNTRXVKT1ZHR3RQdWFJeVhFYmlnCmNUVlArNUEzSDI3b2ZROTdNN1J6
        VHgycWEvZkNTcm03OWZNb3dXcWNHQ00KLS0tIGVCelZOOGQ2Z2dTd2VRSituYU9S
        a3U2SXlEL2MzYTZ2cGViVkY4cWxiS28KDdFwIItKmJQDfj2rU3xZAqHceOzoIG2H
        rTQperMs3ixNnawduys5t0kOgRiDRDi74lQCIieJdHE6uqAWZoMAgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T11:51:22Z"
  mac: ENC[AES256_GCM,data:m/s7mJX+gn+y7Us7JfqlfrmU5c1qoiyLsZ2eFjOw3AnVgT+9tbWhT3uz/4J2eQhlcwJdDeIIhXNpIYIkQFe5IxoZatN8EjL/9cbaiqCVo4D28vWm8E5IstfBGWWPleU81+c/Lbb2Hc7SNKQDPCEVujBQwy/jOXT8d4mO69moiyY=,iv:7w3hM21oX2oVU8OYeRkKw1l9wVbDFx9lIizXShJ18yM=,tag:jEBnkvVK6XPkvtR4HPST5g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
