# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cgK+zvgjwZ5w7Wc1ggdbcwtLjwlh7PPHuDif4W4U8/A=,iv:jlKOMKh+OOGiNr11GbElKfJtArgke/0uPGCF1KLO4lc=,tag:Rw0KzHCCxkG/2MMGp6Mb5Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYkRjVlgvMWxqL3RPTi9i
        NTh5NjBvUko2UnRsdmJJZUhlQ0NpMko4WG1rClJKSXVDVTdPdldic3FNUmNPOWxt
        VVNmVjNJdzBCWnlCdmtSTDdsbVVhc28KLS0tIE5iL0dBUTVkbUVTbmZFeEhYZWtq
        Mk0wQ0RaMG9HTGlYdGpqeFkvQjEwakUK6l7eI+GwtzZRvX8VC1IQFZSIwll95anX
        L16iqYOBTJAHdErwcqjFClvG8WgybNVUK9LU7ncV7eiWi8nb0w4fNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T12:36:56Z"
  mac: ENC[AES256_GCM,data:UIMaDARzsBBsdPtFyJT0dBLPKn0ETTDfAePPsWGQhjIxP9YWjwNWZf7PuW1LQpxrQRqy5uds8FkI+jZFV+zvtmYDDdrZ0qTlS48yX4AHZi3RmIDKuBCfazpsmG/DBoAC8PHoawkpxbCHKFZWGrWOeeH46M7O5ChvKr2PNTpvESI=,iv:R0Zr1lxBOS6SIUpeFIYtC2gUHiS2sfphc+vNDYsk+TE=,tag:Dm2TZ8kEL2kvWmU3fTPHbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
