apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:FySzY78eIw==,iv:ZrBWCyJDo1j5V7U1sfU4MrXD9GnvxX103VBVrYEsXrs=,tag:Lkyfff/9yCLvphVxiwf88w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMW5XNzQ0QWVvbFJMU2Zk
        d2dYaXlKZlMwM0JGazQ1TGVybld4dDhXeG5BCndqaDBGZ2VsZWFPUTI4TC9qam9Z
        am9Ma0xrSkllS1hUTEFpZTFKSEJFbXMKLS0tIHVUZFhXd09GMHF4aWNVYmhza3pD
        RE5GbUl4aUR3cGNIdzY0cjVHNWpDMTQKxhX1bWITWDxOArtOXuK52dpqTR7TVnQ0
        /YZgVSron2Z+rd+jsm4ZWIoO2KQPvcRctBMnGLzh6I/Akg4CmwTT3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T11:32:39Z"
  mac: ENC[AES256_GCM,data:tcqFhMFoK0hqc19V8CR/lGM5oW998mFk8uDRdTsCuM17j1Xkb72iYl9c4/isQwXAdgosjflb8Bnno+yMhXOWf64LfRZthEAODYJkjddV76txb7WdXI7tFwAE+EpK0MYh/o1GRY0Pq7hGuIJJUHTPsgmA3myI3xPuqTut4UW6fxw=,iv:9J4ZY04Dmfiao0gIhMCHHZ1CgWMvMOIeAUFnKzSIL9o=,tag:pS/q63+n+Z2ebN4RkqpS7Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
