apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:8qWqX0C9PRn9D+G2ReTeZc/LqkZfLfnG7YGuPOMuTIvA8mygXmDbFC4C2yqoLoXvk8ZO/R951UqBAbMo0nCLAU0qGDQxAQ+lmDU=,iv:N8TH7jroWMnED1HEX0T+eEKrd268wg7iS++s3VM2U7o=,tag:fYlfuSdosIwn11wy2SG1WA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaEVBT2h1WlVBcW9XQ2hF
        bWwzVmZtWDN1VEpla3BZQ0I2OTh4N2tEZlQwCmVzdk55WS81ZUJDaU1EeFBYUFRq
        SHhIdXcyMURJMHE0MlEwOEtLMEplRUkKLS0tIHpwVXFvRmpIVmt0dldyQmUzWGk0
        ZDQ3V2xLNlBYcmVYNXpiZXJpQVNyUzgKTCNGBAk8hjHXu9a2RIPOhuOwbJDu+m30
        1+sjKGlAMBnP8o3RwrD0ENo2EJsfbhaPmaIgJPUZzoMzFtevYy87Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T12:36:56Z"
  mac: ENC[AES256_GCM,data:nxNQMaKLyMB+ZeARJEw2SwFGdlbFdah4g8ZbguG/twX0r0O3gahDy2WLl+C0MBtvh0XoZPMn8VO4VHKHQ1zMpe8Ykao/ozR86WsVdI4C96+qLWMvgVJB8B106i6xopc6lMDtuSu85B03nxmn3A1TaPfW0b0cw5z42tHqnNyoIJM=,iv:2s3gbQXgKtG9gKzzTLExLakJVpPeQUtT0OVEk9CJt/g=,tag:G0SU1C8P2NQsLvYIltVUjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
