# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:XCstDhnjC/QLPzqFoOD+oVe/WLCPIisysyCi9C6SbqTvEaotZNDJiA==,iv:LahS/JsYgHI9VOlF4tNHPOVPtO76QIYYkfFascKNou0=,tag:S+cHqzzkObPBjIn9dg/sEA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1eaursuyh4545jvv69jftkl9k35y7ucrxsjcytz5kegxaugnsyqsqrxp4en
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTmRZbEZtUEJxU3FXMGdP
        TkRnY0ZuM2FsSXdOM0lraTRjYmJKY25Gc1FRClRMQnlJdXpUaXFsNjhuNzNVMVdo
        VTdDRXk3bFRpY3F1WGxHcEZGQnhpT2cKLS0tIGgwV0xKVkZWWXlSdWFuYU1ML2pa
        b3JKNW1BcE5rOUZ1cElkaFlVNWFWNzgKcaT5nWg3+7D+iL6SWnPlOMWXi0o1Efl4
        xcQghzr5L47SvD7rH5gq65P9Uru0iJkNPI3VqWXVlbTBUAlye5l0zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T09:46:51Z"
  mac: ENC[AES256_GCM,data:64qm9en+xkoraq8sXVGhGzAl4+Yb6bCkrEoafqiXnjGbkD+qZMiDBeiDL6J3D2eJHyHDAj0VEpYqNIfub+K2vfoZgIuE/qRSpfXBwGN3N1UOciUt85Uy28Lua47d8VBr46kbXLXIBw7tm/eemn4flF90wZ5uK91Tb/lQkwhyFm0=,iv:9DELlIqu0CmghEkJkHMWC4YFoKSE2i3b6rv4FMMjcgs=,tag:FB7Wc7ALrLnAPftQI/SC4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
