---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: static-web
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      static-web:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: nginx
              tag: alpine
            env:
              PORT: &port 80
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
            volumeMounts:
              - name: static-content
                mountPath: /usr/share/nginx/html
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: static-web
        ports:
          http:
            port: *port
    configMaps:
      static-content:
        enabled: true
        data:
          index.html: |
            <!DOCTYPE html>
            <html>
            <head>
              <title>Hello from Kubernetes!</title>
              <style>
                body {
                  font-family: Arial, sans-serif;
                  margin: 0;
                  padding: 30px;
                  background-color: #f5f5f5;
                }
                .container {
                  max-width: 800px;
                  margin: 0 auto;
                  background-color: white;
                  padding: 30px;
                  border-radius: 10px;
                  box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                }
                h1 { color: #3498db; }
                p { line-height: 1.6; }
              </style>
            </head>
            <body>
              <div class="container">
                <h1>Hello World from Kubernetes!</h1>
                <p>This is a simple static web page served from a container in your Kubernetes cluster.</p>
                <p>Congratulations! If you can see this, your deployment was successful.</p>
              </div>
            </body>
            </html>
    persistence:
      static-content:
        enabled: true
        type: configMap
        name: static-content-static-web
        globalMounts:
          - path: /usr/share/nginx/html
    ingress:
      app:
        className: internal
        hosts:
          - host: "static-web.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http